version : 3

service:
    app:
        build:
            context: .
        ports:
            - "5000:5000"
        voluem:
            - ./src:/src
        command: 
            sh -c "python main.py"